# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'videoplayerframe.ui'
#
# Created: Tue Dec 21 23:20:42 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(755, 110)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Frame.sizePolicy().hasHeightForWidth())
        Frame.setSizePolicy(sizePolicy)
        Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.gridLayout = QtGui.QGridLayout(Frame)
        self.gridLayout.setObjectName("gridLayout")
        self.seekSlider = phonon.Phonon.SeekSlider(Frame)
        self.seekSlider.setObjectName("seekSlider")
        self.gridLayout.addWidget(self.seekSlider, 0, 0, 1, 5)
        self.volumeSlider = phonon.Phonon.VolumeSlider(Frame)
        self.volumeSlider.setObjectName("volumeSlider")
        self.gridLayout.addWidget(self.volumeSlider, 1, 0, 1, 5)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.previousBTN = QtGui.QPushButton(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.previousBTN.sizePolicy().hasHeightForWidth())
        self.previousBTN.setSizePolicy(sizePolicy)
        self.previousBTN.setObjectName("previousBTN")
        self.horizontalLayout.addWidget(self.previousBTN)
        self.playBTN = QtGui.QPushButton(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playBTN.sizePolicy().hasHeightForWidth())
        self.playBTN.setSizePolicy(sizePolicy)
        self.playBTN.setObjectName("playBTN")
        self.horizontalLayout.addWidget(self.playBTN)
        self.nextBTN = QtGui.QPushButton(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nextBTN.sizePolicy().hasHeightForWidth())
        self.nextBTN.setSizePolicy(sizePolicy)
        self.nextBTN.setObjectName("nextBTN")
        self.horizontalLayout.addWidget(self.nextBTN)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(84, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 1, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.playlistBTN = QtGui.QPushButton(Frame)
        self.playlistBTN.setObjectName("playlistBTN")
        self.horizontalLayout_3.addWidget(self.playlistBTN)
        self.enhanceBTN = QtGui.QPushButton(Frame)
        self.enhanceBTN.setObjectName("enhanceBTN")
        self.horizontalLayout_3.addWidget(self.enhanceBTN)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(138, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 3, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.subsBTN = QtGui.QPushButton(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.subsBTN.sizePolicy().hasHeightForWidth())
        self.subsBTN.setSizePolicy(sizePolicy)
        self.subsBTN.setObjectName("subsBTN")
        self.horizontalLayout_2.addWidget(self.subsBTN)
        self.fullscreenBTN = QtGui.QPushButton(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fullscreenBTN.sizePolicy().hasHeightForWidth())
        self.fullscreenBTN.setSizePolicy(sizePolicy)
        self.fullscreenBTN.setObjectName("fullscreenBTN")
        self.horizontalLayout_2.addWidget(self.fullscreenBTN)
        self.labelTime = QtGui.QLabel(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTime.sizePolicy().hasHeightForWidth())
        self.labelTime.setSizePolicy(sizePolicy)
        self.labelTime.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelTime.setObjectName("labelTime")
        self.horizontalLayout_2.addWidget(self.labelTime)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 4, 1, 1)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(QtGui.QApplication.translate("Frame", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.previousBTN.setText(QtGui.QApplication.translate("Frame", "previous", None, QtGui.QApplication.UnicodeUTF8))
        self.playBTN.setText(QtGui.QApplication.translate("Frame", "play", None, QtGui.QApplication.UnicodeUTF8))
        self.nextBTN.setText(QtGui.QApplication.translate("Frame", "next", None, QtGui.QApplication.UnicodeUTF8))
        self.playlistBTN.setText(QtGui.QApplication.translate("Frame", "playlist", None, QtGui.QApplication.UnicodeUTF8))
        self.enhanceBTN.setText(QtGui.QApplication.translate("Frame", "enhance", None, QtGui.QApplication.UnicodeUTF8))
        self.subsBTN.setText(QtGui.QApplication.translate("Frame", "subs", None, QtGui.QApplication.UnicodeUTF8))
        self.fullscreenBTN.setText(QtGui.QApplication.translate("Frame", "fullscreen", None, QtGui.QApplication.UnicodeUTF8))
        self.labelTime.setText(QtGui.QApplication.translate("Frame", "00:00:00 / 00:00:00", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import phonon
